# Generated by Django 3.2 on 2024-05-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish_date',)},
        ),
    ]
